//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TAREA_5Entities : DbContext
    {
        public TAREA_5Entities()
            : base("name=TAREA_5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTACTO> CONTACTOes { get; set; }
        public virtual DbSet<EVENTO> EVENTOS { get; set; }
    
        [DbFunction("TAREA_5Entities", "buscar_fecha")]
        public virtual IQueryable<buscar_fecha_Result> buscar_fecha(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<buscar_fecha_Result>("[TAREA_5Entities].[buscar_fecha](@fecha)", fechaParameter);
        }
    }
}
